[package]
name = "rwm"
version = "0.1.0"
authors = ["Spyros Roum <spyrosr1@gmail.com>"]
description = "The Rusty Window Manager"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
x11rb = "0.7"
polling = "2.0"
common = { path = "../common" }
serde = "1"
serde_json = "1"
toml = "0.5"
anyhow = "1"
